(NEW_AMENDMENT, RETURNED_AMENDMENT, AMENDMENT_BEING_PROCESSED,
        ACCEPTED_AMENDMENT_WAITING_FOR_PRINTING,
        ACCEPTED_AMENDMENT_BEING_TRANSLATED, PRINTED_AMENDMENT,
        PASSED_AMENDMENT, FAILED_AMENDMENT) = range(8)
