(NEW_DRAFT, RETURNED_DRAFT, DRAFT_BEING_PROCESSED, 
        ACCEPTED_DRAFT_WAITING_FOR_PRINTING, ACCEPTED_DRAFT_BEING_TRANSLATED,
        PRINTED_DRAFT, PASSED_RESOLUTION_BEING_PROCESSED,
        PASSED_RESOLUTION_WAITING_FOR_PRINTING, PRINTED_FINAL_RESOLUTION,
        FAILED_RESOLUTION, SERIOUS_WTF) = range(11)
